### ISSUE TITLE
Does not work if the filepath has blank spaces

### ISSUE THREAD

**Issue by MikelVazquez** [atarabi/vscode-ae-script-runner#1]
Hey! Thanks for you script! It's awesome to be able to use visual studio code for programming instead of the bloody ExtendedScript Toolkit. But there is a problem when you execute a script that is in a filepath that has blank spaces (i.e.: c:\my scripts\) 

Could this be fixed? I would appreciate it too much. Thanks!

**Comment by atarabi** [comment]
I'm sorry for my late response.
I've fixed it!

**Comment by MikelVazquez** [comment]
Thanks!!!
